services:
  demo-app:
    build: .
    container_name: demo-metrics-app
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    container_name: demo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - demo-app
    profiles:
      - prometheus
  alloy:
    image: grafana/alloy:latest
    container_name: demo-alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    depends_on:
      - demo-app
    profiles:
      - alloy