global:
  scrape_interval: __SCRAPE_INTERVAL__
scrape_configs:
  - job_name: "__SCRAPE_JOB_NAME__"
    static_configs:
      - targets: ["__APP_TARGET__"]
remote_write:
  - url: "__ES_ENDPOINT__/_prometheus/api/v1/write"
    authorization:
      type: ApiKey
      credentials: __ES_API_KEY__
